FROM ghcr.io/alis-is/ascend:latest-alpine-ami

COPY bootstrap /bootstrap

ENV ASCEND_APPS=/mavpay/
ENV APPS_BOOTSTRAP=/bootstrap

RUN mkdir -p /mavpay

RUN wget -q https://github.com/mavryk-network/mavbake/raw/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh

RUN apk add --no-cache shadow && \
	useradd -r -s /bin/false ascend
