name: Manual Container Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'latest'

jobs:
  build-containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and publish ubuntu container
      uses: docker/build-push-action@v4
      with:
        file: ./containers/ubuntu/Containerfile
        context: ./containers/ubuntu
        platforms: linux/amd64,linux/arm64
        build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        tags: ghcr.io/tez-capital/tezbake:${{ github.event.inputs.version }}-ubuntu,ghcr.io/tez-capital/tezbake:latest-ubuntu,ghcr.io/tez-capital/tezbake:latest
        push: true
        provenance: false

    - name: Build and publish alpine container
      uses: docker/build-push-action@v4
      with:
        file: ./containers/alpine/Containerfile
        context: ./containers/alpine
        platforms: linux/amd64,linux/arm64
        build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        tags: ghcr.io/tez-capital/tezbake:${{ github.event.inputs.version }}-alpine,ghcr.io/tez-capital/tezbake:latest-alpine
        push: true
        provenance: false

